== Module {module-number}: Introduction to Bridge
:imagesdir: images
:source-highlighter: rouge
:icons: font

ifdef::logo[]
image::{logo}[align="left", pdfwidth=25%]
endif::[]

{SP}
{SP}

[discrete]
=== Learning Objectives
[grid=none,frame=none,cols="25%a,75%a"]
|===
|image::agenda.svg[align="left",pdfwidth=50%]|
ifeval::["{artifact-type}" != "SLIDE"]
Upon completion of this module, learners will be able to:

* Describe Overview

* Understand History of Bridge

* Understand Basic Rules

endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Describe Overview

* Understand History of Bridge

endif::[]
|===

<<<


=== Overview

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
An overview of the game of bridge, its history, and basic rules.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* An overview of the game of bridge, its history, and basic rules.

endif::[]



<<<

=== History of Bridge

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Explore the origins and evolution of bridge as a card game.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Explore the origins and evolution of bridge as a card game.

endif::[]



<<<

=== Basic Rules

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Learn the fundamental rules of bridge, including the structure of the game.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Learn the fundamental rules of bridge, including the structure of the game.

endif::[]



<<<

=== Understanding the Deck

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Get familiar with the bridge deck, card values, and suits.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Get familiar with the bridge deck, card values, and suits.

endif::[]



<<<

=== The Objective of the Game

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Understand the goals of playing bridge and how to score points.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Understand the goals of playing bridge and how to score points.

endif::[]



<<<

=== Bridge Terminology

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Familiarize yourself with common terms and jargon used in bridge.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Familiarize yourself with common terms and jargon used in bridge.

endif::[]



<<<


[appendix]
=== Glossary
ifeval::["{artifact-type}" != "SLIDE"]
ifdef::glossary[]
- {glossary}
endif::[]
endif::[]

[discrete]
=== Additional Notes
ifeval::["{artifact-type}" == "IG"]
*Instructor Tip:* Reinforce cross-module connections or common pitfalls.
endif::[]