== Module {module-number}: Bridge Etiquette and Strategy
:imagesdir: images
:source-highlighter: rouge
:icons: font

ifdef::logo[]
image::{logo}[align="left", pdfwidth=25%]
endif::[]

{SP}
{SP}

[discrete]
=== Learning Objectives
[grid=none,frame=none,cols="25%a,75%a"]
|===
|image::agenda.svg[align="left",pdfwidth=50%]|
ifeval::["{artifact-type}" != "SLIDE"]
Upon completion of this module, learners will be able to:

* Describe Overview

* Understand Bridge Etiquette

* Understand Psychology of Bridge

endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Describe Overview

* Understand Bridge Etiquette

endif::[]
|===

<<<


=== Overview

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Understand the social aspects of bridge and develop strategic thinking.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Understand the social aspects of bridge and develop strategic thinking.

endif::[]



<<<

=== Bridge Etiquette

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Learn the dos and don&#39;ts of playing bridge socially and competitively.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Learn the dos and don&#39;ts of playing bridge socially and competitively.

endif::[]



<<<

=== Psychology of Bridge

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Explore the psychological aspects of playing bridge and how to use them to your advantage.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Explore the psychological aspects of playing bridge and how to use them to your advantage.

endif::[]



<<<

=== Analyzing Your Play

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Develop skills to analyze your own play and improve over time.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Develop skills to analyze your own play and improve over time.

endif::[]



<<<

=== Team Play Strategies

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Learn strategies for playing effectively in team formats.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Learn strategies for playing effectively in team formats.

endif::[]



<<<

=== Common Mistakes to Avoid

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Identify common pitfalls in bridge and how to avoid them.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Identify common pitfalls in bridge and how to avoid them.

endif::[]



<<<


[appendix]
=== Glossary
ifeval::["{artifact-type}" != "SLIDE"]
ifdef::glossary[]
- {glossary}
endif::[]
endif::[]

[discrete]
=== Additional Notes
ifeval::["{artifact-type}" == "IG"]
*Instructor Tip:* Reinforce cross-module connections or common pitfalls.
endif::[]