== Module {module-number}: Advanced Bidding Techniques
:imagesdir: images
:source-highlighter: rouge
:icons: font

ifdef::logo[]
image::{logo}[align="left", pdfwidth=25%]
endif::[]

{SP}
{SP}

[discrete]
=== Learning Objectives
[grid=none,frame=none,cols="25%a,75%a"]
|===
|image::agenda.svg[align="left",pdfwidth=50%]|
ifeval::["{artifact-type}" != "SLIDE"]
Upon completion of this module, learners will be able to:

* Describe Overview

* Understand Advanced Bidding Conventions

* Understand Preemptive Bids

endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Describe Overview

* Understand Advanced Bidding Conventions

endif::[]
|===

<<<


=== Overview

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Delve into more complex bidding strategies and conventions.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Delve into more complex bidding strategies and conventions.

endif::[]



<<<

=== Advanced Bidding Conventions

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Explore advanced conventions like Stayman and Blackwood.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Explore advanced conventions like Stayman and Blackwood.

endif::[]



<<<

=== Preemptive Bids

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Learn the purpose and strategy behind preemptive bidding.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Learn the purpose and strategy behind preemptive bidding.

endif::[]



<<<

=== Competitive Bidding

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Understand how to bid in competitive scenarios against opponents.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Understand how to bid in competitive scenarios against opponents.

endif::[]



<<<

=== Overcalls and Doubles

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Master the use of overcalls and doubles in bidding.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Master the use of overcalls and doubles in bidding.

endif::[]



<<<

=== Game and Slam Bids

ifeval::["{artifact-type}" == "IG"]
*Instructor Note:* 
endif::[]

ifeval::["{artifact-type}" != "SLIDE"]
Learn how to identify and bid for games and slams.


endif::[]

ifeval::["{artifact-type}" == "SLIDE"]

* Learn how to identify and bid for games and slams.

endif::[]



<<<


[appendix]
=== Glossary
ifeval::["{artifact-type}" != "SLIDE"]
ifdef::glossary[]
- {glossary}
endif::[]
endif::[]

[discrete]
=== Additional Notes
ifeval::["{artifact-type}" == "IG"]
*Instructor Tip:* Reinforce cross-module connections or common pitfalls.
endif::[]